### PR TITLE
Add examples

### LINKED ISSUE #42: Add examples for user easier to discover how to use backon

### PR DESCRIPTION
**Pull request by balroggg**
Fix #42

### CODE REVIEW

**Comment by Xuanwo** [comment]
Thanks a lot!

**Comment by balroggg** [comment]
Maybe useful to add example with closure.
Something like
```
let f = || async {
    //
    Err::<(), anyhow::Error>(anyhow::anyhow!("not retryable"))
};
let backoff = todo!();
f.retry(&backoff).await();
```

**Comment by Xuanwo** [comment]
> Maybe useful to add example with closure.

LGTM! This PR is good enough to get merged now. Do you want to add it in this PR or start a new one?

**Comment by balroggg** [comment]
> > Maybe useful to add example with closure.
> 
> 
> 
> LGTM! This PR is good enough to get merged now. Do you want to add it in this PR or start a new one?

Nice! I think in new one.

**Pull request merged**
