### PR TITLE
Adjust `Retry::when` to use `fn -> Into<bool>`

### PR DESCRIPTION
**Pull request by bheylin**
This allows boolean expressions and readable types such as the provided `enum Decide` to be used in both the `Retry::when` and `RetryWithContext::when` methods.

The below example defines a fn to be given to the `Retry::when` method and follows the Rust API [guideline](https://rust-lang.github.io/api-guidelines/type-safety.html?highlight=bool#arguments-convey-meaning-through-types-not-bool-or-option-c-custom-type) of favoring named bools instead of easily confused boolean literals:

```rust
fn should_retry(err: &reqwest::Error) -> backon::Decide {
    let Some(status) = err.status() else {
        warn!("The `reqwest::Error` should be the outcome of a Response");
        return Decide::Stop;
    };

    if status == StatusCode::REQUEST_TIMEOUT {
        warn!("Client request timeout");
        return Decide::Retry;
    }

    let status_category = match StatusCodeCategory::try_from(status) {
        Ok(s) => s,
        Err(err) => {
            error!("{err}");
            return Decide::Stop;
        }
    };

    match status_category {
        StatusCodeCategory::Informational(_) | StatusCodeCategory::Success(_) => {
            warn!(
                "The informal and success status ranges should not result in an `request::Error`"
            );
            Decide::Stop
        }
        StatusCodeCategory::Redirection(_) => {
            warn!("Redirection received, we don't handle that yet.");
            Decide::Stop
        }
        StatusCodeCategory::ClientError(status) => {
            warn!("Client error, response code: {status}",);
            Decide::Stop
        }
        StatusCodeCategory::ServerError(status) => {
            warn!("Server error, response code: {status}");
            Decide::Retry
        }
    }
}
```

Compare the above to the raw bool version (and try spot the bug):

```rust
fn should_retry(err: &reqwest::Error) -> bool {
    let Some(status) = err.status() else {
        warn!("The `reqwest::Error` should be the outcome of a Response");
        return false;
    };

    if status == StatusCode::REQUEST_TIMEOUT {
        warn!("Client request timeout");
        return true;
    }

    let status_category = match StatusCodeCategory::try_from(status) {
        Ok(s) => s,
        Err(err) => {
            error!("{err}");
            return false;
        }
    };

    match status_category {
        StatusCodeCategory::Informational(_) | StatusCodeCategory::Success(_) => {
            warn!(
                "The informal and success status ranges should not result in an `request::Error`"
            );
            false
        }
        StatusCodeCategory::Redirection(_) => {
            warn!("Redirection received, we don't handle that yet.");
            false
        }
        StatusCodeCategory::ClientError(status) => {
            warn!("Client error, response code: {status}",);
            false
        }
        StatusCodeCategory::ServerError(status) => {
            warn!("Server error, response code: {status}");
            false
        }
    }
}
```

### CODE REVIEW

**Review by Xuanwo — COMMENTED** [review]
Thank you for your PR. The idea is interesting, but I believe it doesn't need to be included in backon. Users can define their own enum to make their `when` logic easier to read, so there's no need for us to provide such a type.

**Comment by bheylin** [comment]
> Thank you for your PR. The idea is interesting, but I believe it doesn't need to be included in backon. Users can define their own enum to make their `when` logic easier to read, so there's no need for us to provide such a type.

Are you open to the `DE: Into<bool>` signature change? This would allow both boolean expressions and custom enums suppled by the user.

```rust
    pub fn when<RN, DE>(self, retryable: RN) -> Retry<B, T, E, Fut, FutureFn, SF, RN, NF>
    where
        RN: FnMut(&E) -> DE,
        DE: Into<bool>,
```

**Comment by Xuanwo** [comment]
> Are you open to the `DE: Into<bool>` signature change? This would allow both boolean expressions and custom enums suppled by the user without having to call `Decide::Retry.into()` in the `when` closure.

Hi, I prefer not to change it. Returning a `bool` is simple and clear, but providing `impl Into<bool>` adds another generic parameter, which increases the maintenance burden.

**Comment by bheylin** [comment]
> > Are you open to the `DE: Into<bool>` signature change? This would allow both boolean expressions and custom enums suppled by the user without having to call `Decide::Retry.into()` in the `when` closure.
> 
> Hi, I prefer not to change it. Returning a `bool` is simple and clear, but providing `impl Into<bool>` adds another generic parameter, which increases the maintenance burden.

All good! I'll close the PR.

**Comment by Xuanwo** [comment]
Thank you @bheylin for your work on this. I look forward to collaborating again in the future.

**Pull request closed without merging**
